server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:h2:tcp://localhost/~/querydsl
    #username: sa
    #password:
    #driver-class-name: oracle.jdbc
    #schema: classpath:data.sql
    #initialization-mode: always
    url: jdbc:mariadb://patrick-lab.cjeq2ffynlc2.ap-northeast-2.rds.amazonaws.com:3306/patricklab?characterEncoding=UTF-8&serverTimezone=UTC
    username: patricklab
    password: patricklab
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  org.hibernate.SQL: debug
  org.hibernate.type: trace
#logging:
#  pattern:
#    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%X{traceId}] %-5level %logger{35} %msg %n"


# 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