server:
  port: 9992

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patrick-lab?useUnicode=true&serverTimezone=Asia/Seoul
    username: patrick-lab
    password: patrick-lab
    hikari:
      maximum-pool-size: 40
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 10
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql


patrick:
  name: patrick main
  age: ${random.int}logging

# Mybatis
mybatis:
  type-aliases-package: me.patrick.mybatis.mapper
  mapper-locations:
    - static/mapper/*.xml
